trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SVCsonarforDesktopApp'
    organization: 'blazertest'
    scannerMode: 'MSBuild'
    projectKey: 'BlazerTest_DotNet_DesktopApp'
    projectName: 'DesktopApp' 


- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.2.x'
  inputs:
    version: 2.2.x
    includePreviewVersions: true
    performMultiLevelLookup: true


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    arguments: --output $(Build.ArtifactStagingDirectory)

- task: SonarCloudAnalyze@1

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'Calculator'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
